export const colors = {
  primary: '$indigo9',

  bgBase: '$slate1',
  bgSubtle: '$slate2',
  bgBaseHover: '$slate3',
  bgShade: '#F8F9FB',
  bgBorder: '$slate5',
  bgBorderSolid: '#E0E1E5',
  bgSelected: '#slate4',
  bgSelectedHover: '#E4EBFE',
  bgSelectedBorder: '#CAD2FF',

  labelTitle: '$slate12',
  labelBase: '$slate11',
  labelMuted: '#6B7076',
  labelFaint: '#90949D',
  labelLink: '#90949D',

  buttonBg: '$indigo9',
  buttonBorder: '$indigo9',
  buttonBgHover: '$indigo10',
  buttonBorderHover: '$indigo10',

  buttonSecondaryBg: '$slate6',
  buttonSecondaryBorder: '$slate8',
  buttonSecondaryBgHover: '$slate7',
  buttonSecondaryBorderHover: '$slate9',

  buttonLabel: '$indigo12',

  controlLabel: '#FFFFFF',
  controlSelectedBg: '#F0F3FA',
  controlSelectLabel: '#1E2EB9',
  controlBase: '#6E79D5',
  controlBaseHighlight: '#6E79D5',
  controlSecondary: '#FFFFF',
  controlSecondaryHighlight: '#F4F5F9',

  inputBg: '$slate1',
  inputBgSubtle: '$slate2',
  inputLabel: '$slate11',
  inputLabelFaint: '$slate9',
  inputLabelMuted: '$slate10',
  inputColor: '$slate12',
  inputPlaceholder: '$slate9',
  inputBorder: '$slate6',
  inputBorderHover: '$slate7',
  inputBorderFocus: '$indigo10',

  landingBg: '$indigo1',
  landingSubtleBg: '$indigo2',
  landingButtonBg: '$indigo9',
  landingButtonBgHover: '$indigo10',
  landingButtonText: '$indigo12',
  landingBorder: '$indigo10',
  landingInputBg: '$indigo1',
  landingInputBorder: '$indigo3',
  landingInputBorderHover: '$indigo4',
  landingInputBorderFocus: '$indigo9',
  landingCardBorder: '$indigo3',
  landingCardBg: '$indigo1',
  landingCardSubtleBg: '$indigo2',
  landingCardButtonText: '$indigo4',
  landingLabelTitle: '$slate12',
  landingLabelMuted: '#989cac',
  landingAccentBg: '$slate11'
}
