query StorageDirectory($path: String!) {
  storageDirectory(path: $path) {
    path
    parentFolder {
      ...FolderFragment
    }
    bucket {
      ...BucketFragment
    }
    folders {
      ...FolderFragment
    }
    subFolders {
      ...FolderFragment
    }
    files {
      ...FileFragment
    }
  }
}
