mutation UserConfirmRegistrationWithToken($confirmationToken: String!) {
  userConfirmRegistrationWithToken(confirmationToken: $confirmationToken) {
    authenticatable {
      email
    }
    credentials {
      accessToken
      client
      uid
      tokenType
      expiry
    }
  }
}
