mutation UserConfirmRegistrationWithToken($confirmationToken: String!) {
  userConfirmRegistrationWithToken(confirmationToken: $confirmationToken) {
    authenticatable {
      ...UserFragment
    }
    credentials {
      ...CredentialFragment
    }
  }
}
