mutation UserUpdatePasswordWithToken(
  $password: String!
  $passwordConfirmation: String!
  $resetPasswordToken: String!
) {
  userUpdatePasswordWithToken(
    password: $password
    passwordConfirmation: $passwordConfirmation
    resetPasswordToken: $resetPasswordToken
  ) {
    authenticatable {
      ...UserFragment
    }
    credentials {
      ...CredentialFragment
    }
  }
}
